<template>
  <div class="app-container">
    <el-form ref="queryRef" :model="queryParams" :inline="true" v-show="showSearch"><el-form-item label="优惠券名称" prop="couponName"><el-input v-model="queryParams.couponName" clearable @keyup.enter="getList" /></el-form-item><el-form-item label="状态" prop="status"><el-select v-model="queryParams.status" clearable><el-option label="启用" value="0" /><el-option label="停用" value="1" /></el-select></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="getList">查询</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item></el-form>
    <el-row :gutter="10" class="mb8"><el-col :span="1.5"><el-button type="primary" plain icon="Plus" v-hasPermi="['shop:coupon:add']" @click="handleAdd">新增优惠券</el-button></el-col><el-col :span="1.5"><el-button type="warning" plain icon="Download" v-hasPermi="['shop:coupon:export']" @click="handleExport">导出</el-button></el-col><right-toolbar v-model:showSearch="showSearch" @queryTable="getList" /></el-row>
    <el-table v-loading="loading" :data="rows"><el-table-column prop="couponId" label="ID" width="80" /><el-table-column prop="couponName" label="优惠券" min-width="180" /><el-table-column label="门槛" width="120"><template #default="scope">{{ money(scope.row.thresholdAmount) }}</template></el-table-column><el-table-column label="优惠" width="120"><template #default="scope">{{ money(scope.row.discountAmount) }}</template></el-table-column><el-table-column prop="totalQuantity" label="总量" width="90" /><el-table-column prop="receivedQuantity" label="已领" width="90" /><el-table-column prop="usedQuantity" label="已用" width="90" /><el-table-column prop="status" label="状态" width="90"><template #default="scope"><el-tag :type="scope.row.status === '0' ? 'success' : 'info'">{{ scope.row.status === '0' ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="220" fixed="right"><template #default="scope"><el-button link type="primary" v-hasPermi="['shop:coupon:edit']" @click="handleUpdate(scope.row)">修改</el-button><el-button link type="primary" v-hasPermi="['shop:coupon:status']" @click="toggle(scope.row)">{{ scope.row.status === '0' ? '停用' : '启用' }}</el-button><el-button link type="danger" v-hasPermi="['shop:coupon:remove']" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" v-model:total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    <el-dialog v-model="open" :title="title" width="720px" append-to-body><el-form ref="couponRef" :model="form" :rules="rules" label-width="110px"><el-row :gutter="18"><el-col :span="12"><el-form-item label="优惠券名称" prop="couponName"><el-input v-model="form.couponName" maxlength="128" /></el-form-item></el-col><el-col :span="12"><el-form-item label="每人限领" prop="limitPerMember"><el-input-number v-model="form.limitPerMember" :min="1" :precision="0" /></el-form-item></el-col><el-col :span="12"><el-form-item label="使用门槛（元）" prop="thresholdYuan"><el-input-number v-model="form.thresholdYuan" :min="0" :precision="2" /></el-form-item></el-col><el-col :span="12"><el-form-item label="优惠金额（元）" prop="discountYuan"><el-input-number v-model="form.discountYuan" :min="0" :precision="2" /></el-form-item></el-col><el-col :span="12"><el-form-item label="发放总量" prop="totalQuantity"><el-input-number v-model="form.totalQuantity" :min="1" :precision="0" /></el-form-item></el-col><el-col :span="12"><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio value="0">启用</el-radio><el-radio value="1">停用</el-radio></el-radio-group></el-form-item></el-col></el-row><el-form-item label="领取时间" prop="receiveRange"><el-date-picker v-model="form.receiveRange" type="datetimerange" value-format="YYYY-MM-DD HH:mm:ss" range-separator="至" start-placeholder="开始时间" end-placeholder="结束时间" /></el-form-item><el-form-item label="有效期"><el-radio-group v-model="form.validityType"><el-radio value="fixed">固定日期</el-radio><el-radio value="days">领取后天数</el-radio></el-radio-group></el-form-item><el-form-item v-if="form.validityType === 'fixed'" label="可用时间" prop="validRange"><el-date-picker v-model="form.validRange" type="datetimerange" value-format="YYYY-MM-DD HH:mm:ss" range-separator="至" start-placeholder="开始时间" end-placeholder="结束时间" /></el-form-item><el-form-item v-else label="有效天数" prop="validDays"><el-input-number v-model="form.validDays" :min="1" :precision="0" /></el-form-item></el-form><template #footer><el-button type="primary" :loading="submitting" @click="submitForm">确定</el-button><el-button @click="open = false">取消</el-button></template></el-dialog>
  </div>
</template>
<script setup name="ShopCoupon">
import { getCurrentInstance, reactive, ref } from 'vue'
import { addCoupon, changeCouponStatus, deleteCoupon, getCoupon, listCoupon, updateCoupon } from '@/api/shop/coupon'
const { proxy } = getCurrentInstance()
const loading = ref(false), showSearch = ref(true), open = ref(false), submitting = ref(false), title = ref(''), rows = ref([]), total = ref(0)
const queryParams = reactive({ pageNum: 1, pageSize: 10, couponName: undefined, status: undefined })
const form = reactive({})
const rules = { couponName: [{ required: true, message: '优惠券名称不能为空', trigger: 'blur' }], totalQuantity: [{ required: true, message: '请填写发放总量', trigger: 'change' }], limitPerMember: [{ required: true, message: '请填写每人限领数量', trigger: 'change' }], receiveRange: [{ required: true, message: '请选择领取时间', trigger: 'change' }] }
const money = value => `¥${(Number(value || 0) / 100).toFixed(2)}`
function resetForm() { Object.assign(form, { couponId: undefined, couponName: '', thresholdYuan: 0, discountYuan: 0, totalQuantity: 1, limitPerMember: 1, status: '0', receiveRange: [], validityType: 'fixed', validRange: [], validDays: undefined }); proxy.resetForm('couponRef') }
function getList() { loading.value = true; listCoupon(queryParams).then(res => { rows.value = res.rows; total.value = res.total }).finally(() => { loading.value = false }) }
function resetQuery() { proxy.resetForm('queryRef'); queryParams.pageNum = 1; getList() }
function handleAdd() { resetForm(); title.value = '新增优惠券'; open.value = true }
function handleUpdate(row) { resetForm(); getCoupon(row.couponId).then(res => { const item = res.data; Object.assign(form, item, { thresholdYuan: Number(item.thresholdAmount || 0) / 100, discountYuan: Number(item.discountAmount || 0) / 100, receiveRange: [item.receiveBeginTime, item.receiveEndTime], validityType: item.validDays ? 'days' : 'fixed', validRange: item.validDays ? [] : [item.validBeginTime, item.validEndTime] }); title.value = '修改优惠券'; open.value = true }) }
function submitForm() { proxy.$refs.couponRef.validate(valid => { if (!valid) return; const [receiveBeginTime, receiveEndTime] = form.receiveRange || []; if (!receiveBeginTime || !receiveEndTime || receiveBeginTime >= receiveEndTime) { proxy.$modal.msgError('领取结束时间必须晚于开始时间'); return }; const thresholdAmount = Math.round(Number(form.thresholdYuan || 0) * 100), discountAmount = Math.round(Number(form.discountYuan || 0) * 100); if (discountAmount > thresholdAmount) { proxy.$modal.msgError('优惠金额不能大于使用门槛'); return }; const payload = { ...form, thresholdAmount, discountAmount, receiveBeginTime, receiveEndTime }; delete payload.thresholdYuan; delete payload.discountYuan; delete payload.receiveRange; delete payload.validRange; if (form.validityType === 'days') { if (!form.validDays) { proxy.$modal.msgError('请填写有效天数'); return }; payload.validBeginTime = null; payload.validEndTime = null } else { const [validBeginTime, validEndTime] = form.validRange || []; if (!validBeginTime || !validEndTime || validBeginTime >= validEndTime) { proxy.$modal.msgError('可用结束时间必须晚于开始时间'); return }; payload.validDays = null; payload.validBeginTime = validBeginTime; payload.validEndTime = validEndTime }; delete payload.validityType; submitting.value = true; (payload.couponId ? updateCoupon(payload) : addCoupon(payload)).then(() => { proxy.$modal.msgSuccess(payload.couponId ? '修改成功' : '新增成功'); open.value = false; getList() }).finally(() => { submitting.value = false }) }) }
function toggle(row) { changeCouponStatus(row.couponId, row.status === '0' ? '1' : '0').then(() => { proxy.$modal.msgSuccess('操作成功'); getList() }) }
function handleExport() { proxy.download('shop/coupon/export', { ...queryParams }, `coupon_${new Date().getTime()}.xlsx`) }
function remove(row) { proxy.$modal.confirm(`确认删除“${row.couponName}”？`).then(() => deleteCoupon(row.couponId)).then(() => { proxy.$modal.msgSuccess('删除成功'); getList() }).catch(() => {}) }
getList()
</script>
