-- 商城首期核心表（MySQL 8.0）。
-- 执行前确认目标库已备份；本脚本不包含 DROP、TRUNCATE 或演示数据。
-- 若 DDL 被中断，先核对 information_schema 中已创建的表、索引和外键，再重新执行。

CREATE TABLE IF NOT EXISTS mall_category (
  category_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  parent_id BIGINT UNSIGNED NULL COMMENT '父分类ID，一级分类为空',
  category_name VARCHAR(64) NOT NULL COMMENT '分类名称',
  level TINYINT UNSIGNED NOT NULL COMMENT '层级，1或2',
  sort_num INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态，0正常 1停用',
  create_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志，0存在 2删除',
  PRIMARY KEY (category_id),
  KEY idx_mall_category_parent_status_sort (parent_id, status, sort_num),
  CONSTRAINT chk_mall_category_level CHECK (level IN (1, 2)),
  CONSTRAINT chk_mall_category_sort CHECK (sort_num >= 0),
  CONSTRAINT fk_mall_category_parent FOREIGN KEY (parent_id) REFERENCES mall_category (category_id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城商品分类';

CREATE TABLE IF NOT EXISTS mall_product (
  product_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商品ID',
  category_id BIGINT UNSIGNED NOT NULL COMMENT '分类ID',
  product_name VARCHAR(128) NOT NULL COMMENT '商品名称',
  subtitle VARCHAR(255) NOT NULL DEFAULT '' COMMENT '副标题',
  main_image VARCHAR(512) NOT NULL DEFAULT '' COMMENT '主图地址',
  images_json JSON NULL COMMENT '图片地址数组',
  detail_html LONGTEXT NULL COMMENT '商品详情HTML',
  product_params_json JSON NULL COMMENT '农产品参数JSON',
  spec_schema_json JSON NULL COMMENT '规格定义JSON',
  status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态，0草稿 1上架 2下架',
  publish_time DATETIME(3) NULL COMMENT '上架时间',
  version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志，0存在 2删除',
  PRIMARY KEY (product_id),
  KEY idx_mall_product_category_status_del (category_id, status, del_flag),
  CONSTRAINT chk_mall_product_version CHECK (version >= 0),
  CONSTRAINT fk_mall_product_category FOREIGN KEY (category_id) REFERENCES mall_category (category_id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城商品SPU';

CREATE TABLE IF NOT EXISTS mall_product_sku (
  sku_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'SKU ID',
  product_id BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  sku_code VARCHAR(64) NOT NULL COMMENT 'SKU业务编码',
  sku_name VARCHAR(128) NOT NULL COMMENT 'SKU名称',
  spec_values_json JSON NULL COMMENT '规格值JSON',
  image_url VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'SKU图片地址',
  sale_price BIGINT NOT NULL COMMENT '销售价，分',
  market_price BIGINT NOT NULL DEFAULT 0 COMMENT '市场价，分',
  available_stock BIGINT NOT NULL DEFAULT 0 COMMENT '可用库存',
  locked_stock BIGINT NOT NULL DEFAULT 0 COMMENT '锁定库存',
  warning_stock BIGINT NOT NULL DEFAULT 0 COMMENT '库存预警值',
  status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态，0启用 1停用',
  version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志，0存在 2删除',
  PRIMARY KEY (sku_id),
  UNIQUE KEY uk_mall_product_sku_code (sku_code),
  KEY idx_mall_product_sku_product_status_del (product_id, status, del_flag),
  CONSTRAINT chk_mall_product_sku_amount CHECK (sale_price >= 0 AND market_price >= 0),
  CONSTRAINT chk_mall_product_sku_stock CHECK (available_stock >= 0 AND locked_stock >= 0 AND warning_stock >= 0),
  CONSTRAINT chk_mall_product_sku_version CHECK (version >= 0),
  CONSTRAINT fk_mall_product_sku_product FOREIGN KEY (product_id) REFERENCES mall_product (product_id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城商品SKU与库存';

CREATE TABLE IF NOT EXISTS mall_member (
  member_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会员ID',
  app_id VARCHAR(64) NOT NULL COMMENT '小程序AppID',
  open_id VARCHAR(128) NOT NULL COMMENT '小程序OpenID',
  union_id VARCHAR(128) DEFAULT NULL COMMENT '微信UnionID',
  nickname VARCHAR(128) NOT NULL DEFAULT '' COMMENT '昵称',
  avatar_url VARCHAR(512) NOT NULL DEFAULT '' COMMENT '头像地址',
  phone VARCHAR(32) DEFAULT NULL COMMENT '手机号，默认脱敏展示',
  status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态，0正常 1禁用',
  last_login_time DATETIME(3) NULL COMMENT '最近登录时间',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (member_id),
  UNIQUE KEY uk_mall_member_app_open (app_id, open_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城会员';

CREATE TABLE IF NOT EXISTS mall_member_address (
  address_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '地址ID',
  member_id BIGINT UNSIGNED NOT NULL COMMENT '会员ID',
  receiver_name VARCHAR(64) NOT NULL COMMENT '收货人',
  receiver_phone VARCHAR(32) NOT NULL COMMENT '收货电话，默认脱敏展示',
  province_code VARCHAR(32) NOT NULL DEFAULT '' COMMENT '省编码',
  province_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '省名称',
  city_code VARCHAR(32) NOT NULL DEFAULT '' COMMENT '市编码',
  city_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '市名称',
  district_code VARCHAR(32) NOT NULL DEFAULT '' COMMENT '区县编码',
  district_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '区县名称',
  detail_address VARCHAR(255) NOT NULL COMMENT '详细地址，默认脱敏展示',
  is_default CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否默认，0否 1是',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志，0存在 2删除',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (address_id),
  KEY idx_mall_member_address_member_default_del (member_id, is_default, del_flag),
  CONSTRAINT fk_mall_member_address_member FOREIGN KEY (member_id) REFERENCES mall_member (member_id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城会员收货地址';

CREATE TABLE IF NOT EXISTS mall_coupon (
  coupon_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '优惠券ID',
  coupon_name VARCHAR(128) NOT NULL COMMENT '优惠券名称',
  threshold_amount BIGINT NOT NULL DEFAULT 0 COMMENT '使用门槛，分',
  discount_amount BIGINT NOT NULL COMMENT '优惠金额，分',
  total_quantity BIGINT NOT NULL COMMENT '发放总量',
  received_quantity BIGINT NOT NULL DEFAULT 0 COMMENT '已领取数量',
  used_quantity BIGINT NOT NULL DEFAULT 0 COMMENT '已使用数量',
  limit_per_member INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '每人限领数',
  receive_begin_time DATETIME(3) NOT NULL COMMENT '领取开始时间',
  receive_end_time DATETIME(3) NOT NULL COMMENT '领取结束时间',
  valid_days INT UNSIGNED DEFAULT NULL COMMENT '领取后有效天数，固定有效期时为空',
  valid_begin_time DATETIME(3) DEFAULT NULL COMMENT '固定有效期开始时间',
  valid_end_time DATETIME(3) DEFAULT NULL COMMENT '固定有效期结束时间',
  status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态，0启用 1停用',
  version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志，0存在 2删除',
  PRIMARY KEY (coupon_id),
  KEY idx_mall_coupon_status_receive_window (status, receive_begin_time, receive_end_time),
  CONSTRAINT chk_mall_coupon_amount CHECK (threshold_amount >= 0 AND discount_amount >= 0),
  CONSTRAINT chk_mall_coupon_quantity CHECK (total_quantity >= 0 AND received_quantity >= 0 AND used_quantity >= 0 AND received_quantity <= total_quantity AND used_quantity <= received_quantity),
  CONSTRAINT chk_mall_coupon_version CHECK (version >= 0),
  CONSTRAINT chk_mall_coupon_receive_window CHECK (receive_begin_time < receive_end_time),
  CONSTRAINT chk_mall_coupon_validity CHECK ((valid_days IS NOT NULL AND valid_days > 0 AND valid_begin_time IS NULL AND valid_end_time IS NULL) OR (valid_days IS NULL AND valid_begin_time IS NOT NULL AND valid_end_time IS NOT NULL AND valid_begin_time < valid_end_time))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城满减优惠券';

CREATE TABLE IF NOT EXISTS mall_order (
  order_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  order_no VARCHAR(32) NOT NULL COMMENT '订单号',
  member_id BIGINT UNSIGNED NOT NULL COMMENT '会员ID',
  client_request_no VARCHAR(64) NOT NULL COMMENT '客户端幂等请求号',
  order_status VARCHAR(32) NOT NULL COMMENT '订单状态',
  product_amount BIGINT NOT NULL COMMENT '商品总额，分',
  freight_amount BIGINT NOT NULL DEFAULT 0 COMMENT '运费，分',
  discount_amount BIGINT NOT NULL DEFAULT 0 COMMENT '优惠总额，分',
  payable_amount BIGINT NOT NULL COMMENT '应付金额，分',
  paid_amount BIGINT NOT NULL DEFAULT 0 COMMENT '实付金额，分',
  coupon_name_snapshot VARCHAR(128) DEFAULT NULL COMMENT '优惠券名称快照',
  coupon_threshold_snapshot BIGINT DEFAULT NULL COMMENT '优惠券门槛快照，分',
  coupon_discount_snapshot BIGINT DEFAULT NULL COMMENT '优惠券金额快照，分',
  receiver_name VARCHAR(64) NOT NULL COMMENT '收货人快照',
  receiver_phone VARCHAR(32) NOT NULL COMMENT '收货电话快照',
  province_code VARCHAR(32) NOT NULL DEFAULT '' COMMENT '省编码快照',
  province_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '省名称快照',
  city_code VARCHAR(32) NOT NULL DEFAULT '' COMMENT '市编码快照',
  city_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '市名称快照',
  district_code VARCHAR(32) NOT NULL DEFAULT '' COMMENT '区县编码快照',
  district_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '区县名称快照',
  detail_address VARCHAR(255) NOT NULL COMMENT '详细地址快照',
  pay_channel VARCHAR(32) DEFAULT NULL COMMENT '支付渠道',
  channel_trade_no VARCHAR(64) DEFAULT NULL COMMENT '支付渠道交易号',
  pay_prepay_id VARCHAR(128) DEFAULT NULL COMMENT '支付预支付标识',
  logistics_company VARCHAR(128) DEFAULT NULL COMMENT '物流公司',
  logistics_no VARCHAR(64) DEFAULT NULL COMMENT '物流单号',
  buyer_remark VARCHAR(500) DEFAULT NULL COMMENT '买家留言',
  admin_remark VARCHAR(500) DEFAULT NULL COMMENT '后台备注',
  cancel_reason VARCHAR(255) DEFAULT NULL COMMENT '取消原因',
  expire_time DATETIME(3) NOT NULL COMMENT '支付过期时间',
  pay_time DATETIME(3) DEFAULT NULL COMMENT '支付时间',
  ship_time DATETIME(3) DEFAULT NULL COMMENT '发货时间',
  complete_time DATETIME(3) DEFAULT NULL COMMENT '完成时间',
  cancel_time DATETIME(3) DEFAULT NULL COMMENT '取消时间',
  version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (order_id),
  UNIQUE KEY uk_mall_order_no (order_no),
  UNIQUE KEY uk_mall_order_member_request (member_id, client_request_no),
  UNIQUE KEY uk_mall_order_pay_trade (pay_channel, channel_trade_no),
  KEY idx_mall_order_member_status_time (member_id, order_status, create_time),
  KEY idx_mall_order_status_time (order_status, create_time),
  CONSTRAINT chk_mall_order_amount CHECK (product_amount >= 0 AND freight_amount >= 0 AND discount_amount >= 0 AND payable_amount >= 0 AND paid_amount >= 0 AND discount_amount <= product_amount + freight_amount AND payable_amount = product_amount + freight_amount - discount_amount),
  CONSTRAINT chk_mall_order_version CHECK (version >= 0),
  CONSTRAINT fk_mall_order_member FOREIGN KEY (member_id) REFERENCES mall_member (member_id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城订单';

CREATE TABLE IF NOT EXISTS mall_order_item (
  order_item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单明细ID',
  order_id BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  product_id BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  sku_id BIGINT UNSIGNED NOT NULL COMMENT 'SKU ID',
  product_name_snapshot VARCHAR(128) NOT NULL COMMENT '商品名称快照',
  sku_name_snapshot VARCHAR(128) NOT NULL COMMENT 'SKU名称快照',
  spec_values_snapshot JSON NULL COMMENT '规格快照JSON',
  image_url_snapshot VARCHAR(512) NOT NULL DEFAULT '' COMMENT '图片快照',
  sale_price_snapshot BIGINT NOT NULL COMMENT '销售单价快照，分',
  quantity INT UNSIGNED NOT NULL COMMENT '购买数量',
  line_amount BIGINT NOT NULL COMMENT '商品行金额，分',
  discount_amount BIGINT NOT NULL DEFAULT 0 COMMENT '优惠分摊金额，分',
  payable_amount BIGINT NOT NULL COMMENT '明细应付金额，分',
  PRIMARY KEY (order_item_id),
  KEY idx_mall_order_item_order (order_id),
  CONSTRAINT chk_mall_order_item_amount CHECK (sale_price_snapshot >= 0 AND line_amount >= 0 AND discount_amount >= 0 AND payable_amount >= 0 AND discount_amount <= line_amount AND payable_amount = line_amount - discount_amount),
  CONSTRAINT chk_mall_order_item_quantity CHECK (quantity > 0),
  CONSTRAINT fk_mall_order_item_order FOREIGN KEY (order_id) REFERENCES mall_order (order_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mall_order_item_product FOREIGN KEY (product_id) REFERENCES mall_product (product_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mall_order_item_sku FOREIGN KEY (sku_id) REFERENCES mall_product_sku (sku_id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城订单明细';

CREATE TABLE IF NOT EXISTS mall_order_log (
  order_log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单日志ID',
  order_id BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  action VARCHAR(64) NOT NULL COMMENT '操作动作',
  before_status VARCHAR(32) DEFAULT NULL COMMENT '操作前订单状态',
  after_status VARCHAR(32) NOT NULL COMMENT '操作后订单状态',
  operator_type VARCHAR(32) NOT NULL COMMENT '操作者类型，ADMIN MEMBER SYSTEM',
  operator_id VARCHAR(64) DEFAULT NULL COMMENT '操作者ID',
  description VARCHAR(500) NOT NULL DEFAULT '' COMMENT '脱敏操作说明',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (order_log_id),
  KEY idx_mall_order_log_order_time (order_id, create_time),
  CONSTRAINT fk_mall_order_log_order FOREIGN KEY (order_id) REFERENCES mall_order (order_id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城订单状态日志';

CREATE TABLE IF NOT EXISTS mall_member_coupon (
  member_coupon_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会员券ID',
  coupon_no VARCHAR(32) NOT NULL COMMENT '会员券凭证号',
  coupon_id BIGINT UNSIGNED NOT NULL COMMENT '优惠券ID',
  member_id BIGINT UNSIGNED NOT NULL COMMENT '会员ID',
  coupon_name_snapshot VARCHAR(128) NOT NULL COMMENT '优惠券名称快照',
  threshold_amount_snapshot BIGINT NOT NULL COMMENT '门槛快照，分',
  discount_amount_snapshot BIGINT NOT NULL COMMENT '优惠金额快照，分',
  status VARCHAR(32) NOT NULL COMMENT '状态，AVAILABLE LOCKED USED EXPIRED VOID',
  valid_begin_time DATETIME(3) NOT NULL COMMENT '生效时间',
  valid_end_time DATETIME(3) NOT NULL COMMENT '失效时间',
  locked_order_id BIGINT UNSIGNED DEFAULT NULL COMMENT '锁定订单ID',
  used_order_id BIGINT UNSIGNED DEFAULT NULL COMMENT '使用订单ID',
  receive_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '领取时间',
  use_time DATETIME(3) DEFAULT NULL COMMENT '使用时间',
  version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (member_coupon_id),
  UNIQUE KEY uk_mall_member_coupon_no (coupon_no),
  UNIQUE KEY uk_mall_member_coupon_locked_order (locked_order_id),
  UNIQUE KEY uk_mall_member_coupon_used_order (used_order_id),
  KEY idx_mall_member_coupon_member_status_end (member_id, status, valid_end_time),
  KEY idx_mall_member_coupon_coupon_member (coupon_id, member_id),
  CONSTRAINT chk_mall_member_coupon_amount CHECK (threshold_amount_snapshot >= 0 AND discount_amount_snapshot >= 0),
  CONSTRAINT chk_mall_member_coupon_version CHECK (version >= 0),
  CONSTRAINT chk_mall_member_coupon_window CHECK (valid_begin_time < valid_end_time),
  CONSTRAINT fk_mall_member_coupon_coupon FOREIGN KEY (coupon_id) REFERENCES mall_coupon (coupon_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mall_member_coupon_member FOREIGN KEY (member_id) REFERENCES mall_member (member_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mall_member_coupon_locked_order FOREIGN KEY (locked_order_id) REFERENCES mall_order (order_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mall_member_coupon_used_order FOREIGN KEY (used_order_id) REFERENCES mall_order (order_id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城会员优惠券';

CREATE TABLE IF NOT EXISTS mall_inventory_log (
  inventory_log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '库存流水ID',
  sku_id BIGINT UNSIGNED NOT NULL COMMENT 'SKU ID',
  biz_type VARCHAR(32) NOT NULL COMMENT '业务类型，INBOUND ADJUST LOCK RELEASE DEDUCT',
  biz_no VARCHAR(64) NOT NULL COMMENT '业务编号',
  available_change BIGINT NOT NULL COMMENT '可用库存变更量',
  locked_change BIGINT NOT NULL COMMENT '锁定库存变更量',
  available_before BIGINT NOT NULL COMMENT '变更前可用库存',
  available_after BIGINT NOT NULL COMMENT '变更后可用库存',
  locked_before BIGINT NOT NULL COMMENT '变更前锁定库存',
  locked_after BIGINT NOT NULL COMMENT '变更后锁定库存',
  operator_type VARCHAR(32) NOT NULL COMMENT '操作者类型，ADMIN MEMBER SYSTEM',
  operator_id VARCHAR(64) DEFAULT NULL COMMENT '操作者ID',
  reason VARCHAR(500) NOT NULL DEFAULT '' COMMENT '变更原因',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (inventory_log_id),
  UNIQUE KEY uk_mall_inventory_log_sku_biz (sku_id, biz_type, biz_no),
  KEY idx_mall_inventory_log_sku_time (sku_id, create_time),
  CONSTRAINT chk_mall_inventory_log_stock CHECK (available_before >= 0 AND available_after >= 0 AND locked_before >= 0 AND locked_after >= 0 AND available_after = available_before + available_change AND locked_after = locked_before + locked_change),
  CONSTRAINT fk_mall_inventory_log_sku FOREIGN KEY (sku_id) REFERENCES mall_product_sku (sku_id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城库存流水';

CREATE TABLE IF NOT EXISTS mall_banner (
  banner_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Banner ID',
  title VARCHAR(128) NOT NULL COMMENT '标题',
  image_url VARCHAR(512) NOT NULL COMMENT '图片地址',
  jump_type VARCHAR(32) NOT NULL COMMENT '跳转类型，NONE PRODUCT CATEGORY PATH',
  target_value VARCHAR(512) DEFAULT NULL COMMENT '跳转目标，由跳转类型解释',
  sort_num INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态，0启用 1停用',
  begin_time DATETIME(3) NOT NULL COMMENT '展示开始时间',
  end_time DATETIME(3) NOT NULL COMMENT '展示结束时间',
  create_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  update_by VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志，0存在 2删除',
  PRIMARY KEY (banner_id),
  KEY idx_mall_banner_status_sort_window (status, sort_num, begin_time, end_time),
  CONSTRAINT chk_mall_banner_sort CHECK (sort_num >= 0),
  CONSTRAINT chk_mall_banner_window CHECK (begin_time < end_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城首页Banner';

-- 回滚说明：本期不提供自动回滚 SQL，避免误删已产生的订单、库存和券凭证数据。
