package com.ruoyi.system.domain.shop;

import java.util.List;
import com.ruoyi.common.annotation.Excel;
import com.ruoyi.common.core.domain.BaseEntity;

public class MallOrder extends BaseEntity
{
    private Long orderId; @Excel(name="订单号") private String orderNo; @Excel(name="会员ID", cellType=Excel.ColumnType.NUMERIC) private Long memberId; private String clientRequestNo; @Excel(name="订单状态", readConverterExp="PENDING_PAYMENT=待支付,PENDING_SHIPMENT=待发货,SHIPPED=已发货,COMPLETED=已完成,CANCELED=已取消") private String orderStatus;
    private Long productAmount; private Long freightAmount; private Long discountAmount; @Excel(name="应付金额(分)", cellType=Excel.ColumnType.NUMERIC) private Long payableAmount; @Excel(name="实付金额(分)", cellType=Excel.ColumnType.NUMERIC) private Long paidAmount;
    private String couponNameSnapshot; private Long couponThresholdSnapshot; private Long couponDiscountSnapshot;
    @Excel(name="收件人") private String receiverName; @Excel(name="收件电话") private String receiverPhone; private String provinceCode; private String provinceName; private String cityCode; private String cityName; private String districtCode; private String districtName; private String detailAddress;
    private String payChannel; private String channelTradeNo;
    private String logisticsCompany; private String logisticsNo; private String buyerRemark; private String adminRemark; private String cancelReason;
    private List<MallOrderItem> items;
    public Long getOrderId(){return orderId;} public void setOrderId(Long v){orderId=v;} public String getOrderNo(){return orderNo;} public void setOrderNo(String v){orderNo=v;} public Long getMemberId(){return memberId;} public void setMemberId(Long v){memberId=v;} public String getClientRequestNo(){return clientRequestNo;} public void setClientRequestNo(String v){clientRequestNo=v;} public String getOrderStatus(){return orderStatus;} public void setOrderStatus(String v){orderStatus=v;}
    public Long getProductAmount(){return productAmount;} public void setProductAmount(Long v){productAmount=v;} public Long getFreightAmount(){return freightAmount;} public void setFreightAmount(Long v){freightAmount=v;} public Long getDiscountAmount(){return discountAmount;} public void setDiscountAmount(Long v){discountAmount=v;} public Long getPayableAmount(){return payableAmount;} public void setPayableAmount(Long v){payableAmount=v;} public Long getPaidAmount(){return paidAmount;} public void setPaidAmount(Long v){paidAmount=v;}
    public String getCouponNameSnapshot(){return couponNameSnapshot;} public void setCouponNameSnapshot(String v){couponNameSnapshot=v;} public Long getCouponThresholdSnapshot(){return couponThresholdSnapshot;} public void setCouponThresholdSnapshot(Long v){couponThresholdSnapshot=v;} public Long getCouponDiscountSnapshot(){return couponDiscountSnapshot;} public void setCouponDiscountSnapshot(Long v){couponDiscountSnapshot=v;}
    public String getReceiverName(){return receiverName;} public void setReceiverName(String v){receiverName=v;} public String getReceiverPhone(){return receiverPhone;} public void setReceiverPhone(String v){receiverPhone=v;} public String getProvinceCode(){return provinceCode;} public void setProvinceCode(String v){provinceCode=v;} public String getProvinceName(){return provinceName;} public void setProvinceName(String v){provinceName=v;} public String getCityCode(){return cityCode;} public void setCityCode(String v){cityCode=v;} public String getCityName(){return cityName;} public void setCityName(String v){cityName=v;} public String getDistrictCode(){return districtCode;} public void setDistrictCode(String v){districtCode=v;} public String getDistrictName(){return districtName;} public void setDistrictName(String v){districtName=v;} public String getDetailAddress(){return detailAddress;} public void setDetailAddress(String v){detailAddress=v;}
    public String getPayChannel(){return payChannel;} public void setPayChannel(String v){payChannel=v;} public String getChannelTradeNo(){return channelTradeNo;} public void setChannelTradeNo(String v){channelTradeNo=v;}
    public String getLogisticsCompany(){return logisticsCompany;} public void setLogisticsCompany(String v){logisticsCompany=v;} public String getLogisticsNo(){return logisticsNo;} public void setLogisticsNo(String v){logisticsNo=v;} public String getBuyerRemark(){return buyerRemark;} public void setBuyerRemark(String v){buyerRemark=v;} public String getAdminRemark(){return adminRemark;} public void setAdminRemark(String v){adminRemark=v;} public String getCancelReason(){return cancelReason;} public void setCancelReason(String v){cancelReason=v;} public List<MallOrderItem> getItems(){return items;} public void setItems(List<MallOrderItem> v){items=v;}
}
