<template>
  <div class="app-container">
    <el-form ref="queryRef" :model="queryParams" :inline="true" v-show="showSearch">
      <el-form-item label="标题" prop="title"><el-input v-model="queryParams.title" placeholder="请输入 Banner 标题" clearable @keyup.enter="getList" /></el-form-item>
      <el-form-item label="状态" prop="status"><el-select v-model="queryParams.status" placeholder="全部状态" clearable><el-option label="启用" value="0" /><el-option label="停用" value="1" /></el-select></el-form-item>
      <el-form-item><el-button type="primary" icon="Search" @click="getList">查询</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item>
    </el-form>
    <el-row :gutter="10" class="mb8"><el-col :span="1.5"><el-button type="primary" plain icon="Plus" v-hasPermi="['shop:banner:add']" @click="handleAdd">新增 Banner</el-button></el-col><el-col :span="1.5"><el-button type="warning" plain icon="Download" v-hasPermi="['shop:banner:export']" @click="handleExport">导出</el-button></el-col><right-toolbar v-model:showSearch="showSearch" @queryTable="getList" /></el-row>
    <el-table v-loading="loading" :data="rows"><el-table-column prop="bannerId" label="ID" width="80" /><el-table-column prop="title" label="标题" min-width="180" /><el-table-column prop="imageUrl" label="图片" width="90"><template #default="scope"><image-preview :src="scope.row.imageUrl" :width="42" :height="42" /></template></el-table-column><el-table-column prop="jumpType" label="跳转类型" width="110" /><el-table-column prop="beginTime" label="展示开始" width="180"><template #default="scope">{{ parseTime(scope.row.beginTime) }}</template></el-table-column><el-table-column prop="endTime" label="展示结束" width="180"><template #default="scope">{{ parseTime(scope.row.endTime) }}</template></el-table-column><el-table-column prop="status" label="状态" width="90"><template #default="scope"><el-tag :type="scope.row.status === '0' ? 'success' : 'info'">{{ scope.row.status === '0' ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="220" fixed="right"><template #default="scope"><el-button link type="primary" v-hasPermi="['shop:banner:edit']" @click="handleUpdate(scope.row)">修改</el-button><el-button link type="primary" v-hasPermi="['shop:banner:status']" @click="toggle(scope.row)">{{ scope.row.status === '0' ? '停用' : '启用' }}</el-button><el-button link type="danger" v-hasPermi="['shop:banner:remove']" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" v-model:total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    <el-dialog v-model="open" :title="title" width="680px" append-to-body><el-form ref="bannerRef" :model="form" :rules="rules" label-width="100px"><el-form-item label="标题" prop="title"><el-input v-model="form.title" maxlength="128" /></el-form-item><el-form-item label="图片" prop="imageUrl"><el-upload :action="uploadUrl" :headers="uploadHeaders" :show-file-list="false" :on-success="uploadSuccess"><el-button icon="Upload">上传图片</el-button></el-upload><image-preview v-if="form.imageUrl" :src="form.imageUrl" :width="80" :height="40" /></el-form-item><el-form-item label="跳转类型" prop="jumpType"><el-select v-model="form.jumpType"><el-option label="不跳转" value="NONE" /><el-option label="商品" value="PRODUCT" /><el-option label="分类" value="CATEGORY" /><el-option label="小程序路径" value="PATH" /></el-select></el-form-item><el-form-item v-if="form.jumpType !== 'NONE'" label="跳转目标" prop="targetValue"><el-input v-model="form.targetValue" placeholder="请输入商品、分类 ID 或小程序路径" /></el-form-item><el-form-item label="展示时间" prop="displayRange"><el-date-picker v-model="form.displayRange" type="datetimerange" value-format="YYYY-MM-DD HH:mm:ss" range-separator="至" start-placeholder="开始时间" end-placeholder="结束时间" /></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sortNum" :min="0" /></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio value="0">启用</el-radio><el-radio value="1">停用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button type="primary" :loading="submitting" @click="submitForm">确定</el-button><el-button @click="open = false">取消</el-button></template></el-dialog>
  </div>
</template>
<script setup name="ShopBanner">
import { getCurrentInstance, reactive, ref } from 'vue'
import { getToken } from '@/utils/auth'
import { addBanner, changeBannerStatus, deleteBanner, getBanner, listBanner, updateBanner } from '@/api/shop/banner'
const { proxy } = getCurrentInstance()
const loading = ref(false), showSearch = ref(true), open = ref(false), submitting = ref(false), title = ref(''), rows = ref([]), total = ref(0)
const queryParams = reactive({ pageNum: 1, pageSize: 10, title: undefined, status: undefined })
const form = reactive({})
const rules = { title: [{ required: true, message: '标题不能为空', trigger: 'blur' }], imageUrl: [{ required: true, message: '请上传图片', trigger: 'change' }], displayRange: [{ required: true, message: '请选择展示时间', trigger: 'change' }] }
const uploadUrl = import.meta.env.VITE_APP_BASE_API + '/common/upload', uploadHeaders = { Authorization: `Bearer ${getToken()}` }
function resetForm() { Object.assign(form, { bannerId: undefined, title: '', imageUrl: '', jumpType: 'NONE', targetValue: '', sortNum: 0, status: '0', displayRange: [] }); proxy.resetForm('bannerRef') }
function getList() { loading.value = true; listBanner(queryParams).then(res => { rows.value = res.rows; total.value = res.total }).finally(() => { loading.value = false }) }
function resetQuery() { proxy.resetForm('queryRef'); queryParams.pageNum = 1; getList() }
function handleAdd() { resetForm(); title.value = '新增 Banner'; open.value = true }
function handleUpdate(row) { resetForm(); getBanner(row.bannerId).then(res => { Object.assign(form, res.data, { displayRange: [res.data.beginTime, res.data.endTime] }); title.value = '修改 Banner'; open.value = true }) }
function uploadSuccess(res) { if (res.code === 200) form.imageUrl = res.url; else proxy.$modal.msgError(res.msg || '上传失败') }
function submitForm() { proxy.$refs.bannerRef.validate(valid => { if (!valid) return; if (form.jumpType !== 'NONE' && !form.targetValue.trim()) { proxy.$modal.msgError('请填写跳转目标'); return }; const [beginTime, endTime] = form.displayRange || []; if (!beginTime || !endTime || beginTime >= endTime) { proxy.$modal.msgError('展示结束时间必须晚于开始时间'); return }; submitting.value = true; const payload = { ...form, beginTime, endTime }; delete payload.displayRange; (payload.bannerId ? updateBanner(payload) : addBanner(payload)).then(() => { proxy.$modal.msgSuccess(payload.bannerId ? '修改成功' : '新增成功'); open.value = false; getList() }).finally(() => { submitting.value = false }) }) }
function toggle(row) { changeBannerStatus(row.bannerId, row.status === '0' ? '1' : '0').then(() => { proxy.$modal.msgSuccess('操作成功'); getList() }) }
function handleExport() { proxy.download('shop/banner/export', { ...queryParams }, `banner_${new Date().getTime()}.xlsx`) }
function remove(row) { proxy.$modal.confirm(`确认删除“${row.title}”？`).then(() => deleteBanner(row.bannerId)).then(() => { proxy.$modal.msgSuccess('删除成功'); getList() }).catch(() => {}) }
getList()
</script>
