<template>
  <div class="app-container">
    <el-form ref="queryRef" :model="queryParams" :inline="true" v-show="showSearch">
      <el-form-item label="商品名称" prop="productName"><el-input v-model="queryParams.productName" placeholder="请输入商品名称" clearable @keyup.enter="getList" /></el-form-item>
      <el-form-item label="状态" prop="status"><el-select v-model="queryParams.status" placeholder="全部状态" clearable><el-option label="草稿" value="0" /><el-option label="上架" value="1" /><el-option label="下架" value="2" /></el-select></el-form-item>
      <el-form-item><el-button type="primary" icon="Search" @click="getList">查询</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item>
    </el-form>
    <el-row :gutter="10" class="mb8"><el-col :span="1.5"><el-button type="primary" plain icon="Plus" v-hasPermi="['shop:product:add']" @click="handleAdd">新增商品</el-button></el-col><el-col :span="1.5"><el-button type="warning" plain icon="Download" v-hasPermi="['shop:product:export']" @click="handleExport">导出</el-button></el-col><right-toolbar v-model:showSearch="showSearch" @queryTable="getList" /></el-row>
    <el-table v-loading="loading" :data="productList"><el-table-column prop="productId" label="ID" width="80" /><el-table-column prop="mainImage" label="主图" width="85"><template #default="scope"><image-preview :src="scope.row.mainImage" :width="42" :height="42" /></template></el-table-column><el-table-column prop="productName" label="商品名称" min-width="180" /><el-table-column prop="categoryId" label="分类ID" width="100" /><el-table-column prop="status" label="状态" width="90"><template #default="scope"><dict-tag :options="productStatus" :value="scope.row.status" /></template></el-table-column><el-table-column prop="createTime" label="创建时间" width="180"><template #default="scope">{{ parseTime(scope.row.createTime) }}</template></el-table-column><el-table-column label="操作" width="310" fixed="right"><template #default="scope"><el-button link type="primary" icon="Edit" v-hasPermi="['shop:product:edit']" @click="handleUpdate(scope.row)">修改</el-button><el-button link type="primary" v-hasPermi="['shop:product:stock']" @click="openInventory(scope.row)">库存调整</el-button><el-button link type="primary" v-hasPermi="['shop:product:status']" @click="handleStatus(scope.row)">{{ scope.row.status === '1' ? '下架' : '上架' }}</el-button><el-button link type="danger" icon="Delete" v-hasPermi="['shop:product:remove']" @click="handleDelete(scope.row)">删除</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" v-model:total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    <el-dialog v-model="open" :title="title" width="900px" append-to-body><el-form ref="productRef" :model="form" :rules="rules" label-width="90px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="商品名称" prop="productName"><el-input v-model="form.productName" maxlength="128" /></el-form-item></el-col><el-col :span="12"><el-form-item label="商品分类" prop="categoryId"><el-select v-model="form.categoryId" filterable><el-option v-for="item in categoryOptions" :key="item.categoryId" :label="item.categoryName" :value="item.categoryId" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="副标题"><el-input v-model="form.subtitle" maxlength="255" /></el-form-item></el-col><el-col :span="12"><el-form-item label="主图"><el-upload :action="uploadUrl" :headers="uploadHeaders" :show-file-list="false" :on-success="uploadSuccess"><el-button icon="Upload">上传图片</el-button></el-upload><image-preview v-if="form.mainImage" :src="form.mainImage" :width="36" :height="36" /></el-form-item></el-col></el-row><el-form-item label="商品详情"><el-input v-model="form.detailHtml" type="textarea" :rows="3" /></el-form-item><el-divider content-position="left">SKU</el-divider><el-button type="primary" plain size="small" icon="Plus" @click="addSku">新增 SKU</el-button><el-table :data="form.skus" class="mt10" border><el-table-column label="编码" min-width="135"><template #default="scope"><el-input v-model="scope.row.skuCode" /></template></el-table-column><el-table-column label="名称" min-width="135"><template #default="scope"><el-input v-model="scope.row.skuName" /></template></el-table-column><el-table-column label="销售价（元）" width="145"><template #default="scope"><el-input-number v-model="scope.row.salePriceYuan" :min="0" :precision="2" /></template></el-table-column><el-table-column label="市场价（元）" width="145"><template #default="scope"><el-input-number v-model="scope.row.marketPriceYuan" :min="0" :precision="2" /></template></el-table-column><el-table-column label="预警库存" width="120"><template #default="scope"><el-input-number v-model="scope.row.warningStock" :min="0" /></template></el-table-column><el-table-column label="状态" width="100"><template #default="scope"><el-select v-model="scope.row.status"><el-option label="启用" value="0" /><el-option label="停用" value="1" /></el-select></template></el-table-column><el-table-column label="操作" width="70"><template #default="scope"><el-button link type="danger" icon="Delete" @click="form.skus.splice(scope.$index, 1)" /></template></el-table-column></el-table></el-form><template #footer><el-button type="primary" :loading="submitting" @click="submitForm">确定</el-button><el-button @click="open=false">取消</el-button></template></el-dialog>
    <el-dialog v-model="inventoryOpen" title="库存调整" width="480px" append-to-body><el-form :model="inventoryForm" label-width="90px"><el-form-item label="SKU"><el-select v-model="inventoryForm.skuId" style="width: 100%"><el-option v-for="sku in inventorySkus" :key="sku.skuId" :label="`${sku.skuName}（可用库存 ${sku.availableStock}）`" :value="sku.skuId" /></el-select></el-form-item><el-form-item label="调整类型"><el-radio-group v-model="inventoryForm.bizType"><el-radio value="INBOUND">入库</el-radio><el-radio value="ADJUST">盘点增加</el-radio></el-radio-group></el-form-item><el-form-item label="调整数量"><el-input-number v-model="inventoryForm.quantity" :min="1" :precision="0" /></el-form-item><el-form-item label="调整原因"><el-input v-model="inventoryForm.reason" type="textarea" maxlength="200" show-word-limit /></el-form-item></el-form><template #footer><el-button type="primary" :loading="adjusting" @click="submitInventory">确认调整</el-button><el-button @click="inventoryOpen = false">取消</el-button></template></el-dialog>
  </div>
</template>
<script setup name="ShopProduct">
import { getCurrentInstance, reactive, ref, toRefs } from 'vue'
import { getToken } from '@/utils/auth'
import { listCategory } from '@/api/shop/category'
import { addProduct, changeProductStatus, delProduct, getProduct, listProduct, updateProduct } from '@/api/shop/product'
import { adjustInventory } from '@/api/shop/inventory'
const { proxy } = getCurrentInstance(); const loading=ref(false),showSearch=ref(true),open=ref(false),submitting=ref(false),title=ref(''),total=ref(0),productList=ref([]),categoryOptions=ref([]),inventoryOpen=ref(false),adjusting=ref(false),inventorySkus=ref([])
const productStatus = [{ label:'草稿',value:'0',elTagType:'info'},{label:'上架',value:'1',elTagType:'success'},{label:'下架',value:'2',elTagType:'danger'}]
const uploadUrl = import.meta.env.VITE_APP_BASE_API + '/common/upload', uploadHeaders = { Authorization: `Bearer ${getToken()}` }
const data=reactive({form:{},queryParams:{pageNum:1,pageSize:10,productName:undefined,status:undefined},rules:{productName:[{required:true,message:'商品名称不能为空',trigger:'blur'}],categoryId:[{required:true,message:'请选择商品分类',trigger:'change'}]}}); const { form,queryParams,rules }=toRefs(data)
const inventoryForm = reactive({ skuId: undefined, bizType: 'INBOUND', quantity: 1, reason: '' })
function getList(){loading.value=true;listProduct(queryParams.value).then(res=>{productList.value=res.rows;total.value=res.total}).finally(()=>loading.value=false)}
function loadCategories(){listCategory({status:'0'}).then(res=>{categoryOptions.value=res.data.filter(item=>item.level===2)})}
function reset(){form.value={productId:undefined,categoryId:undefined,productName:'',subtitle:'',mainImage:'',detailHtml:'',skus:[]};proxy.resetForm('productRef')}
function resetQuery(){proxy.resetForm('queryRef');queryParams.value.pageNum=1;getList()}
function addSku(){form.value.skus.push({skuCode:'',skuName:'',salePriceYuan:0,marketPriceYuan:0,warningStock:0,status:'0'})}
function handleAdd(){reset();addSku();loadCategories();title.value='新增商品';open.value=true}
function handleUpdate(row){reset();loadCategories();getProduct(row.productId).then(res=>{form.value=res.data;form.value.skus=(res.data.skus||[]).map(toSkuForm);title.value='修改商品';open.value=true})}
function toSkuForm(sku){return {...sku,salePriceYuan:Number(sku.salePrice||0)/100,marketPriceYuan:Number(sku.marketPrice||0)/100}}
function uploadSuccess(res){if(res.code===200) form.value.mainImage=res.url;else proxy.$modal.msgError(res.msg||'上传失败')}
function submitForm(){proxy.$refs.productRef.validate(valid=>{if(!valid)return;if(!form.value.skus.length){proxy.$modal.msgError('至少需要一条SKU');return}const payload={...form.value,skus:form.value.skus.map(s=>({...s,salePrice:Math.round(Number(s.salePriceYuan)*100),marketPrice:Math.round(Number(s.marketPriceYuan)*100)}))};submitting.value=true;(payload.productId?updateProduct(payload):addProduct(payload)).then(()=>{proxy.$modal.msgSuccess(payload.productId?'修改成功':'新增成功');open.value=false;getList()}).finally(()=>submitting.value=false)})}
function handleStatus(row){const status=row.status==='1'?'2':'1';proxy.$modal.confirm(`确认${status==='1'?'上架':'下架'}商品“${row.productName}”？`).then(()=>changeProductStatus(row.productId,status)).then(()=>{proxy.$modal.msgSuccess('操作成功');getList()}).catch(()=>{})}
function handleDelete(row){proxy.$modal.confirm(`确认删除商品“${row.productName}”？`).then(()=>delProduct(row.productId)).then(()=>{proxy.$modal.msgSuccess('删除成功');getList()}).catch(()=>{})}
function handleExport(){proxy.download('shop/product/export',{...queryParams.value},`product_${new Date().getTime()}.xlsx`)}
function openInventory(row){getProduct(row.productId).then(res=>{inventorySkus.value=res.data.skus||[];Object.assign(inventoryForm,{skuId:inventorySkus.value[0]?.skuId,bizType:'INBOUND',quantity:1,reason:''});inventoryOpen.value=true})}
function submitInventory(){if(!inventoryForm.skuId||!inventoryForm.quantity||!inventoryForm.reason.trim()){proxy.$modal.msgError('调整原因不能为空');return}adjusting.value=true;adjustInventory(inventoryForm).then(()=>{proxy.$modal.msgSuccess('库存调整成功');inventoryOpen.value=false}).finally(()=>adjusting.value=false)}
loadCategories();getList()
</script>
