<template>
  <div class="shop-admin">
    <div class="shop-admin__topbar">
      <div><span class="shop-admin__eyebrow">RUOYI SHOP OPERATIONS</span><h1>黔山优选 · 运营工作台</h1><p>小程序经营数据总览与日常管理</p></div>
      <div class="shop-admin__top-actions"><el-button plain @click="refresh"><el-icon><Refresh /></el-icon>刷新数据</el-button><el-button type="primary" @click="notify('导出任务已创建')"><el-icon><Download /></el-icon>导出报表</el-button></div>
    </div>

    <div class="shop-admin__tabs">
      <button v-for="tab in tabs" :key="tab.key" :class="{ active: activeTab === tab.key }" @click="activeTab = tab.key"><el-icon><component :is="tab.icon" /></el-icon>{{ tab.label }}</button>
    </div>

    <template v-if="activeTab === 'overview'">
      <div class="shop-admin__welcome"><div><span class="shop-admin__pill">今日经营</span><h2>早上好，运营同学</h2><p>小程序正在稳定运行，今天也要把山里好物送到更多家庭。</p></div><div class="shop-admin__date">{{ today }}<small>数据更新于刚刚</small></div></div>
      <div class="shop-admin__kpis"><article v-for="item in kpis" :key="item.label" class="shop-admin__kpi"><span class="shop-admin__kpi-icon" :class="item.tone"><el-icon><component :is="item.icon" /></el-icon></span><div><small>{{ item.label }}</small><strong>{{ item.value }}</strong><em :class="item.trend < 0 ? 'negative' : ''">{{ item.trend > 0 ? '↑' : '↓' }} {{ Math.abs(item.trend) }}% 较昨日</em></div></article></div>
      <div class="shop-admin__grid shop-admin__grid--main"><section class="shop-admin__panel"><header><div><h3>近 7 日成交趋势</h3><p>订单数与成交金额</p></div><el-select v-model="period" size="small" style="width:110px"><el-option label="近7天" value="7" /><el-option label="近30天" value="30" /></el-select></header><div class="shop-admin__chart"><div v-for="(point, index) in trend" :key="point.day" class="shop-admin__bar-wrap"><span>{{ point.amount }}</span><div class="shop-admin__bar" :style="{ height: `${point.value}%` }" :class="{ hot: index === 5 }"></div><small>{{ point.day }}</small></div></div></section><section class="shop-admin__panel"><header><div><h3>待处理事项</h3><p>需要关注的经营任务</p></div><el-button link type="primary" @click="activeTab='orders'">查看全部</el-button></header><div class="shop-admin__tasks"><button v-for="task in tasks" :key="task.label" @click="activeTab = task.tab"><span :class="task.tone">{{ task.value }}</span><div><strong>{{ task.label }}</strong><small>{{ task.desc }}</small></div><el-icon><ArrowRight /></el-icon></button></div></section></div>
      <div class="shop-admin__grid shop-admin__grid--bottom"><section class="shop-admin__panel"><header><div><h3>热销商品排行</h3><p>按近30日销量排序</p></div><el-button link type="primary" @click="activeTab='products'">商品管理</el-button></header><el-table :data="hotProducts" size="small"><el-table-column prop="name" label="商品" min-width="180" /><el-table-column prop="category" label="分类" width="110" /><el-table-column prop="sales" label="销量" width="90" /><el-table-column prop="amount" label="销售额" width="100" /></el-table></section><section class="shop-admin__panel"><header><div><h3>小程序动态</h3><p>最近更新记录</p></div></header><div class="shop-admin__timeline"><div v-for="item in updates" :key="item.time"><i></i><span><strong>{{ item.title }}</strong><small>{{ item.desc }}</small></span><time>{{ item.time }}</time></div></div></section></div>
    </template>

    <section v-else class="shop-admin__panel shop-admin__module"><header><div><h2>{{ currentTab.label }}</h2><p>{{ currentTab.desc }}</p></div><el-button type="primary" @click="notify(`${currentTab.label}新增入口已预留`)" ><el-icon><Plus /></el-icon>新增{{ currentTab.entity }}</el-button></header><div class="shop-admin__filters"><el-input v-model="keyword" placeholder="搜索名称、编号或手机号" clearable style="width:280px"><template #prefix><el-icon><Search /></el-icon></template></el-input><el-select v-model="status" placeholder="全部状态" clearable style="width:130px"><el-option label="正常" value="正常" /><el-option label="待处理" value="待处理" /><el-option label="已完成" value="已完成" /></el-select><el-button @click="notify('筛选条件已应用')">查询</el-button></div><el-table :data="moduleRows" stripe><el-table-column v-for="column in columns" :key="column.prop" :prop="column.prop" :label="column.label" :min-width="column.width || 120" /><el-table-column label="操作" width="150" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="notify(`已打开${row.name || row.orderNo || row.phone || '记录'}`)">查看</el-button><el-button link type="danger" @click="notify('删除操作已预留')">删除</el-button></template></el-table-column></el-table><div class="shop-admin__pagination"><span>共 {{ moduleRows.length }} 条记录</span><el-pagination small layout="prev, pager, next" :total="moduleRows.length" :page-size="10" /></div></section>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { ArrowRight, Box, Calendar, DataAnalysis, Download, Goods, List, Plus, Refresh, Search, ShoppingCart, User } from '@element-plus/icons-vue'

const activeTab = ref('overview'); const keyword = ref(''); const status = ref(''); const period = ref('7')
const today = new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric' })
const tabs = [{ key: 'overview', label: '经营总览', desc: '小程序核心经营数据与待办', entity: '记录', icon: DataAnalysis }, { key: 'products', label: '商品管理', desc: '维护商品、分类、库存与上下架状态', entity: '商品', icon: Goods }, { key: 'orders', label: '订单管理', desc: '处理订单履约、退款与售后进度', entity: '订单', icon: ShoppingCart }, { key: 'users', label: '用户管理', desc: '查看小程序用户与收货地址数据', entity: '用户', icon: User }, { key: 'campaigns', label: '营销内容', desc: '管理首页 Banner、优惠券与活动入口', entity: '活动', icon: Calendar }]
const kpis = [{ label: '今日订单', value: '86', trend: 12, tone: 'green', icon: ShoppingCart }, { label: '今日成交额', value: '¥12,680', trend: 8.6, tone: 'orange', icon: DataAnalysis }, { label: '待发货', value: '24', trend: 5, tone: 'blue', icon: Box }, { label: '新增用户', value: '1,842', trend: 18, tone: 'purple', icon: User }]
const trend = [{ day: '周一', value: 42, amount: '¥8.2k' }, { day: '周二', value: 56, amount: '¥10.4k' }, { day: '周三', value: 48, amount: '¥9.1k' }, { day: '周四', value: 68, amount: '¥12.8k' }, { day: '周五', value: 62, amount: '¥11.6k' }, { day: '周六', value: 86, amount: '¥16.2k' }, { day: '周日', value: 73, amount: '¥13.7k' }]
const tasks = [{ value: '24', label: '待发货订单', desc: '请在今天 18:00 前处理', tone: 'orange', tab: 'orders' }, { value: '8', label: '库存预警商品', desc: '库存低于安全线', tone: 'blue', tab: 'products' }, { value: '3', label: '售后申请', desc: '等待客服跟进', tone: 'purple', tab: 'orders' }]
const hotProducts = [{ name: '黄精切片 500g', category: '黄精专区', sales: '12,865', amount: '¥512,837' }, { name: '黄精茶礼盒', category: '黄精专区', sales: '9,860', amount: '¥294,814' }, { name: '土蜂蜜 500g', category: '山货干货', sales: '5,210', amount: '¥170,888' }, { name: '菌菇精选礼盒', category: '礼盒专区', sales: '3,021', amount: '¥175,218' }]
const updates = [{ title: '首页 Banner 已更新', desc: '黄精原产地直供活动上线', time: '10:32' }, { title: '新增 8 个商品', desc: '山货干货分类库存同步完成', time: '09:18' }, { title: '订单状态已同步', desc: '昨日 88 笔订单完成发货', time: '昨天' }]
const rows = { products: [{ name: '黄精切片 500g', category: '黄精专区', price: '¥39.80', stock: 428, status: '正常' }, { name: '黄精茶礼盒', category: '黄精专区', price: '¥49.80', stock: 82, status: '待处理' }, { name: '土蜂蜜 500g', category: '山货干货', price: '¥32.80', stock: 215, status: '正常' }], orders: [{ orderNo: '202607180001', name: '张三', amount: '¥109.50', status: '待处理' }, { orderNo: '202607170876', name: '李四', amount: '¥88.80', status: '待发货' }, { orderNo: '202607160543', name: '王五', amount: '¥78.60', status: '已完成' }], users: [{ name: '张三', phone: '138****0001', orders: 12, status: '正常' }, { name: '李四', phone: '139****0008', orders: 8, status: '正常' }, { name: '王五', phone: '156****3321', orders: 3, status: '正常' }], campaigns: [{ name: '黄精原产地直供', type: '首页 Banner', status: '正常' }, { name: '新人优惠券', type: '优惠券', status: '正常' }, { name: '山货礼盒专区', type: '活动入口', status: '待处理' }] }
const currentTab = computed(() => tabs.find(tab => tab.key === activeTab.value) || tabs[0]);
const columns = computed(() => ({ products: [{ prop: 'name', label: '商品名称', width: 190 }, { prop: 'category', label: '分类' }, { prop: 'price', label: '售价' }, { prop: 'stock', label: '库存' }, { prop: 'status', label: '状态' }], orders: [{ prop: 'orderNo', label: '订单编号', width: 160 }, { prop: 'name', label: '用户' }, { prop: 'amount', label: '金额' }, { prop: 'status', label: '状态' }], users: [{ prop: 'name', label: '用户' }, { prop: 'phone', label: '手机号' }, { prop: 'orders', label: '订单数' }, { prop: 'status', label: '状态' }], campaigns: [{ prop: 'name', label: '活动名称', width: 190 }, { prop: 'type', label: '类型' }, { prop: 'status', label: '状态' }] }[activeTab.value] || [])); const moduleRows = computed(() => (rows[activeTab.value] || []).filter(row => !keyword.value || Object.values(row).join(' ').includes(keyword.value)).filter(row => !status.value || row.status === status.value))
const notify = message => ElMessage.success(message); const refresh = () => ElMessage.success('Mock 数据已刷新')
</script>

<style scoped lang="scss">
.shop-admin { min-height: calc(100vh - 84px); padding: 26px 30px 40px; background: #f4f7f2; color: #1e2b22; font-family: "Microsoft YaHei", "PingFang SC", sans-serif; }
.shop-admin__topbar { max-width: 1360px; margin: 0 auto 20px; display:flex; justify-content:space-between; align-items:center; gap:24px; }.shop-admin__eyebrow { color:#4f8a52; letter-spacing:2px; font-size:11px; font-weight:700; }.shop-admin h1 { margin:7px 0 5px; font-size:28px; }.shop-admin__topbar p,.shop-admin__welcome p,.shop-admin__panel header p { margin:0; color:#7b887d; font-size:13px; }.shop-admin__top-actions { display:flex; gap:10px; }
.shop-admin__tabs { max-width:1360px; margin:0 auto 18px; padding:6px; display:flex; gap:5px; background:#fff; border:1px solid #e5ece2; border-radius:8px; }.shop-admin__tabs button { display:flex; align-items:center; gap:7px; padding:11px 18px; border:0; border-radius:6px; background:transparent; color:#718076; cursor:pointer; font-size:13px; }.shop-admin__tabs button.active { background:#e5f2e3; color:#33733e; font-weight:700; }.shop-admin__tabs .el-icon { font-size:16px; }
.shop-admin__welcome,.shop-admin__panel,.shop-admin__kpi { background:#fff; border:1px solid #e4ebe1; border-radius:8px; box-shadow:0 5px 18px rgba(38,66,40,.04); }.shop-admin__welcome { max-width:1360px; margin:0 auto 16px; padding:24px 28px; display:flex; justify-content:space-between; background:linear-gradient(105deg,#e8f5e1,#f9fbf7); }.shop-admin__welcome h2 { margin:10px 0 7px; font-size:21px; }.shop-admin__pill { display:inline-block; padding:4px 10px; border-radius:99px; color:#377746; background:#d5ebd2; font-size:11px; }.shop-admin__date { color:#4b7651; text-align:right; font-size:16px; }.shop-admin__date small { display:block; margin-top:7px; color:#88978b; font-size:11px; }
.shop-admin__kpis { max-width:1360px; margin:0 auto 16px; display:grid; grid-template-columns:repeat(4,1fr); gap:14px; }.shop-admin__kpi { padding:18px; display:flex; align-items:center; gap:14px; }.shop-admin__kpi-icon { width:42px;height:42px;display:grid;place-items:center;border-radius:9px; }.shop-admin__kpi-icon.green{background:#e4f4df;color:#3d8a45}.shop-admin__kpi-icon.orange{background:#fff0e2;color:#ed7c2d}.shop-admin__kpi-icon.blue{background:#e7f0fb;color:#397bc0}.shop-admin__kpi-icon.purple{background:#eee8fb;color:#8364bd}.shop-admin__kpi small,.shop-admin__kpi strong,.shop-admin__kpi em { display:block; }.shop-admin__kpi small{color:#7d8b80;font-size:12px}.shop-admin__kpi strong{margin:5px 0;font-size:24px}.shop-admin__kpi em{color:#37a04c;font-size:11px;font-style:normal}.shop-admin__kpi em.negative{color:#e65d45}
.shop-admin__grid { max-width:1360px; margin:0 auto 16px; display:grid; gap:16px; }.shop-admin__grid--main{grid-template-columns:1.45fr 1fr}.shop-admin__grid--bottom{grid-template-columns:1.45fr 1fr}.shop-admin__panel{padding:20px;overflow:hidden}.shop-admin__panel header{display:flex;align-items:flex-start;justify-content:space-between;gap:15px;margin-bottom:17px}.shop-admin h3,.shop-admin h2{margin:0 0 5px;font-size:16px}.shop-admin__chart{height:220px;display:flex;align-items:flex-end;justify-content:space-around;padding:18px 15px 0;background:linear-gradient(180deg,#fbfdfb,#f5faf3);border-radius:7px}.shop-admin__bar-wrap{height:100%;width:10%;display:flex;align-items:center;flex-direction:column;justify-content:flex-end;gap:7px}.shop-admin__bar-wrap span{font-size:10px;color:#91a092}.shop-admin__bar{width:28px;max-height:155px;border-radius:5px 5px 2px 2px;background:#afd3a9;transition:height .3s}.shop-admin__bar.hot{background:#ef8c53}.shop-admin__bar-wrap small{color:#8a968c;font-size:11px}.shop-admin__tasks{display:grid;gap:7px}.shop-admin__tasks button{display:flex;align-items:center;gap:11px;padding:12px;border:0;border-radius:6px;background:#f8faf7;text-align:left;cursor:pointer}.shop-admin__tasks button:hover{background:#eef6eb}.shop-admin__tasks button>span{min-width:34px;font-weight:700;text-align:center}.shop-admin__tasks button>span.orange{color:#ef7c34}.shop-admin__tasks button>span.blue{color:#3a82c4}.shop-admin__tasks button>span.purple{color:#8462bd}.shop-admin__tasks strong,.shop-admin__tasks small{display:block}.shop-admin__tasks strong{font-size:13px}.shop-admin__tasks small{margin-top:4px;color:#879288;font-size:11px}.shop-admin__tasks .el-icon{margin-left:auto;color:#a7b3a9}.shop-admin__timeline{display:grid;gap:18px}.shop-admin__timeline>div{display:flex;gap:10px;align-items:flex-start}.shop-admin__timeline i{width:8px;height:8px;margin-top:5px;border-radius:50%;background:#6ca86d;box-shadow:0 0 0 4px #e7f2e5}.shop-admin__timeline span{flex:1}.shop-admin__timeline strong,.shop-admin__timeline small{display:block}.shop-admin__timeline strong{font-size:13px}.shop-admin__timeline small{margin-top:4px;color:#859186;font-size:11px}.shop-admin__timeline time{color:#a3afa5;font-size:11px}.shop-admin__module{max-width:1360px;margin:0 auto}.shop-admin__module header h2{font-size:20px}.shop-admin__filters{display:flex;gap:10px;margin-bottom:17px;padding:14px;background:#f7faf5;border-radius:6px}.shop-admin__pagination{display:flex;align-items:center;justify-content:space-between;padding-top:17px;color:#8a968d;font-size:12px}
@media(max-width:900px){.shop-admin{padding:18px}.shop-admin__topbar{align-items:flex-start;flex-direction:column}.shop-admin__tabs{overflow-x:auto}.shop-admin__tabs button{white-space:nowrap;padding:10px 13px}.shop-admin__kpis{grid-template-columns:repeat(2,1fr)}.shop-admin__grid--main,.shop-admin__grid--bottom{grid-template-columns:1fr}.shop-admin__welcome{padding:20px}.shop-admin__filters{flex-wrap:wrap}}
@media(max-width:560px){.shop-admin{padding:12px}.shop-admin h1{font-size:22px}.shop-admin__welcome{display:block}.shop-admin__date{margin-top:15px;text-align:left}.shop-admin__kpi{padding:14px}.shop-admin__kpi strong{font-size:20px}.shop-admin__top-actions .el-button{padding:8px}.shop-admin__filters .el-input{width:100%!important}.shop-admin__filters .el-select{flex:1}}
</style>

